export const FETCH_BEST_REQUEST = 'FETCH_BEST_REQUEST';
export const FETCH_BEST_SUCCESS = 'FETCH_BEST_SUCCESS';
export const FETCH_BEST_FAILURE = 'FETCH_BEST_FAILURE';

export const FETCH_COFFEE_REQUEST = 'FETCH_COFFEE_REQUEST';
export const FETCH_COFFEE_SUCCESS = 'FETCH_COFFEE_SUCCESS';
export const FETCH_COFFEE_FAILURE = 'FETCH_COFFEE_FAILURE';

export const PRODUCTS_FILTERING = 'PRODUCTS_FILTERING';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
